### PR TITLE
resolve #86: add unit tests

### LINKED ISSUE #86: Add unit tests
Connected ticket https://github.com/mgolokhov/dodroid/issues/161
Mockk library is the winner

### LINKED ISSUE #161: How to unit test suspend functions like RoomDatabase.withTransaction?
How to write proper coroutine dispatchers:
https://craigrussell.io/2019/11/unit-testing-coroutine-suspend-functions-using-testcoroutinedispatcher/

Even with dispatchers, a test fails with error:
`java.lang.IllegalStateException: This job has not completed yet`

Initial attempt to mock suspend functions:
https://github.com/mockito/mockito/pull/1032
https://github.com/mockito/mockito/blob/885e69420baa2a382f4394b85dc84cb6fe17fff6/subprojects/kotlinTest/src/test/kotlin/org/mockito/kotlin/SuspendTest.kt

About `RoomDatabase.withTransaction`:
https://medium.com/androiddevelopers/threading-models-in-coroutines-and-android-sqlite-api-6cab11f7eb90
https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5

Hacks with library Mockk:
https://stackoverflow.com/questions/56500576/how-to-mock-android-room-withtransaction-method-with-mockk
https://proandroiddev.com/how-to-unit-test-room-runintransaction-3bac366e13f7

### PR DESCRIPTION
**Pull request by mgolokhov**

### CODE REVIEW

File: app/src/main/java/doit/study/droid/di/AppModule.kt [hunk 1]
```diff
@@ -30,4 +31,8 @@ object AppModule {
                 .fallbackToDestructiveMigration()
                 .build()
     }
+
+    @Singleton
+    @Provides
+    fun provideIoDispatcher() = Dispatchers.IO
```
Comment (mgolokhov) [inline app/src/main/java/doit/study/droid/di/AppModule.kt]: Should be cleaned up

File: app/detekt-baseline.xml [hunk 2]
```diff
@@ -59,5 +58,6 @@
     <ID>TooManyFunctions:QuizMainViewModel.kt$QuizMainViewModel$QuizMainViewModel</ID>
     <ID>TooManyFunctions:QuizPageFragment.kt$QuizPageFragment$QuizPageFragment</ID>
     <ID>TooManyFunctions:QuizPageViewModel.kt$QuizPageViewModel$QuizPageViewModel</ID>
+    <ID>TooManyFunctions:QuizRepository.kt$QuizRepository$QuizRepository</ID>
```
Comment (rinekri) [inline app/detekt-baseline.xml:61]: I think, whitelist isn't a good idea. It will lead to situation when you forgot about changing this file - rather use **file:suppress**. But you should think twice before adding this annotation.

File: app/src/main/java/doit/study/droid/data/QuizRepository.kt [hunk 3]
```diff
@@ -68,26 +68,29 @@ class QuizRepository @Inject constructor(
...
 
-    private suspend fun isThereNewContent(): Boolean = withContext(coroutinesDispatcher.io) {
+    private suspend fun isThereNewContent(): Boolean = withContext(coroutineDispatchers.io) {
         config = quizDataClient.configuration()
         return@withContext config.contentVersion > quizContentVersion.getVersion()
     }
 
-    private suspend fun updateData(quizData: List<QuizData>) = withContext(coroutinesDispatcher.io) {
-        quizDatabase.runInTransaction {
+    private suspend fun preCacheTagsFromDb() {
```
Comment (rinekri) [inline app/src/main/java/doit/study/droid/data/QuizRepository.kt:76]: precache should be as one word: precacheTagsFromDb

File: app/src/test/java/doit/study/droid/data/QuizRepositoryTest.kt [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+    private val fakeQuizDataItem = QuizData(
+            id = 1,
+            text = "text",
+            docRef = "doc",
+            rightAnswers = emptyList(),
+            wrongAnswers = emptyList(),
+            tags = listOf("tag")
+    )
+
+    @Before
```
Comment (rinekri) [inline app/src/test/java/doit/study/droid/data/QuizRepositoryTest.kt:56]: It's a bad idea to use **Before** methods and fields in test class, because each test should be as one scope. You shouldn't scroll test to find what initialized something before. Instead use high ordered functions in each test to init mock data. It's better because you can understand test easier - just at first view.
